server:
  port: 8081

spring:
  application:
    name: auth-keycloak
  datasource:
    url: jdbc:postgresql://localhost:5432/db_auth_keycloak
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/master}
cors:
  allowed-origins: ${ALLOWED_CORS_ORIGINS:*}

keycloak:
  base-url: http://localhost:8080
  realm: master
  client-id: auth-keycloak
  client-secret: xGpHCwyAruZ8GvDFv37b4GbSM49bb6wu
  admin-username: admin
  admin-password: admin