server:
  port: 8081

spring:
  application:
    name: auth-keycloak

  datasource:
    url: jdbc:postgresql://localhost:5432/db_auth_keycloak
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    user: postgres
    password: postgres
    enabled: true
    url: jdbc:postgresql://localhost:5432/db_auth_keycloak
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/my-apps}

cors:
  allowed-origins: ${ALLOWED_CORS_ORIGINS:*}

keycloak:
  base-url: http://localhost:8080
  realm: my-apps
  client-id: auth-keycloak
  client-secret: xHdzfQITWvG3eVy1dRA2jTT9bcWIjT9M
  admin-username: admin
  admin-password: admin