server:
  port: 8081

spring:
  application:
    name: auth-keycloak
  datasource:
    url: jdbc:postgresql://localhost:5432/db_auth_keycloak
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/master}
cors:
  allowed-origins: ${ALLOWED_CORS_ORIGINS:*}

keycloak:
  base-url: http://localhost:8080
  realm: master
  client-id: auth-keycloak
  client-secret: wN2ExJiCT0hjV1l7UjorKCyzUO1D5PVH
  admin-username: admin
  admin-password: admin